---

- hosts: host
  gather_facts: yes
  vars_files:
  - vars/main.yml
  become: yes
  roles:
    - name: common/users
      tags: users
    - geerlingguy.firewall
    - geerlingguy.security
    - geerlingguy.repo-epel
    - geerlingguy.apache
    - geerlingguy.php
