---
- hosts: all
  gather_facts: yes
  vars_files:
  - vars/main.yml
  become: yes
  tasks:
    - name: Selinux
      selinux: state=disabled
  roles:
    - name: common/domains
    - name: common/users
    - geerlingguy.repo-epel
    - geerlingguy.firewall
    - geerlingguy.security
    - geerlingguy.apache
    - geerlingguy.php
