---
- hosts: host
  gather_facts: yes
  become: yes
  roles:
    - geerlingguy.firewall
    - geerlingguy.security
    - geerlingguy.repo-epel
    - geerlingguy.apache
    - geerlingguy.php
    - name: common/users
      tags: users
