---
- hosts: all
  gather_facts: yes
  vars_files:
  - vars/main.yml
  become: yes
  roles:
    - name: common/domains
    - name: common/users
    - geerlingguy.repo-epel
    - geerlingguy.firewall
    - geerlingguy.security
    - geerlingguy.apache
    - geerlingguy.php
    - name: common/selinux
    - name: common/reboot
