---
user_newusers:
  user01:
    detail: "user01"
    pass: "{{ 'ansible' | password_hash('sha256') }}"
    groups: sys
    priv: admin

  wwwtest:
    detail: "wwwtest"
    pass: "{{ 'wwwtest' | password_hash('sha256') }}"
    groups: test
    priv: admin
